yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
cacheFolder: "./.yarn/cache"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
